site_name: DDI Developers docs
repo_url: https://github.com/ddi-developers/docs/
edit_uri: edit/main/docs/

theme: 
  name: material
  language: en
  features:
    - content.action.edit
    - content.code.copy
    - search.suggest
  icon:
    edit: material/pencil
  font:
    text: Roboto
    code: Roboto Mono


markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format